services:
  - type: web
    name: hsil-suicide-analysis-api
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt && mkdir -p data models
    startCommand: python api.py
    envVars:
      - key: PORT
        value: 8000
      - key: ENVIRONMENT
        value: production
      - key: GEMINI_API_KEY
        sync: false
      - key: CSV_PATH
        value: data/Suicide_Detection_sample.csv
      - key: CHUNK_SIZE
        value: 5000
      - key: MAX_CHUNKS
        value: 20
    autoDeploy: true 