services:
  - type: web
    name: hsil-suicide-analysis-api
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt && python download_nltk.py && mkdir -p data models
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker api:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PORT
        value: 8000
      - key: ENVIRONMENT
        value: production
      - key: GEMINI_API_KEY
        sync: false
      - key: CSV_PATH
        value: data/Suicide_Detection_sample.csv
      - key: CHUNK_SIZE
        value: 5000
      - key: MAX_CHUNKS
        value: 20
    autoDeploy: true 