services:
  - type: web
    name: hsil-suicide-analysis-api
    env: python
    region: singapore
    plan: free
    buildCommand: pip install fastapi uvicorn python-dotenv
    startCommand: python api_lite.py
    envVars:
      - key: PORT
        value: 8000
      - key: ENVIRONMENT
        value: production
      - key: GEMINI_API_KEY
        sync: false
      - key: CSV_PATH
        value: data/Suicide_Detection_sample.csv
    autoDeploy: true 